# Generated by Django 3.1.3 on 2020-11-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20201110_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='verify_like',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
